In [42]:
from tensorflow.keras.preprocessing.text import one_hot
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\Deep Joshi\Desktop\Data Analysis\Deep Learning\IMDB Dataset.csv',encoding='utf-8')
df=df.iloc[:1000,:]
df.loc[df['sentiment'] == 'positive' , 'sentiment'] = 1
df.loc[df['sentiment'] == 'negative' , 'sentiment'] = 0

In [43]:
label = np.array(df.review.values.tolist())
target = np.array(df.sentiment.values.tolist())
voc_size=100000
onehot_repr=[one_hot(words,voc_size)for words in label] 
print(onehot_repr)

[[58159, 44736, 80962, 30191, 39740, 85496, 14067, 76211, 58100, 71194, 63209, 63944, 65414, 7332, 79147, 30333, 45290, 67307, 87084, 97603, 14575, 46538, 18394, 95982, 58042, 60918, 16819, 55075, 29094, 29094, 80962, 88330, 17706, 76211, 82407, 55075, 57093, 65414, 85812, 70084, 59676, 94032, 40994, 11722, 44736, 56023, 75391, 50900, 52404, 97603, 87689, 80962, 97033, 35689, 53423, 55075, 46538, 18394, 23148, 20692, 69406, 97466, 80962, 58271, 77558, 32928, 75625, 46538, 69406, 64006, 22948, 41832, 16819, 15242, 93183, 59552, 18848, 32928, 56023, 70084, 18394, 76571, 52404, 80962, 76415, 14059, 44736, 80962, 97033, 29094, 29094, 43843, 18394, 97612, 65414, 14575, 76211, 18394, 80962, 24458, 53569, 93183, 80962, 96053, 21148, 58693, 68649, 41417, 43843, 36772, 28836, 67392, 7428, 23976, 32693, 44600, 43284, 44736, 80962, 52560, 71839, 39304, 80962, 50574, 17564, 28787, 43469, 94032, 19781, 71464, 95333, 36345, 18394, 23148, 42625, 67392, 80962, 35331, 68014, 23976, 18394, 40399, 93183,

In [44]:
max_length = max([len(s.split()) for s in label])
print(max_length)

1296


In [45]:
import numpy as np
from tensorflow.keras.layers import Embedding,Dense,GRU,Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=max_length)
print(embedded_docs)

[[58159 44736 80962 ...     0     0     0]
 [20692 90364 81685 ...     0     0     0]
 [82037 91666 46538 ...     0     0     0]
 ...
 [82037 37173 44802 ...     0     0     0]
 [68045 35464 47616 ...     0     0     0]
 [46538 18394 47616 ...     0     0     0]]


In [46]:
model = Sequential()
model.add(Embedding(voc_size, 100, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 1296, 100)         10000000  
_________________________________________________________________
flatten_2 (Flatten)          (None, 129600)            0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 129601    
Total params: 10,129,601
Trainable params: 10,129,601
Non-trainable params: 0
_________________________________________________________________
None


In [52]:
# fit the model
model.fit(embedded_docs, target, epochs=3, verbose=0)
